// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrSL3Hj7Pbhk06Bnn6GZdHSTZjhWdiOXE',
    appId: '1:64743673510:web:0567c5779844bb197d2e67',
    messagingSenderId: '64743673510',
    projectId: 'antenatal-care-41925',
    authDomain: 'antenatal-care-41925.firebaseapp.com',
    storageBucket: 'antenatal-care-41925.appspot.com',
    measurementId: 'G-RMJK88JVMD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBDed-A85psHMgJCde2ErF9dkFAUzk5aE',
    appId: '1:64743673510:android:328ffe9eababaacc7d2e67',
    messagingSenderId: '64743673510',
    projectId: 'antenatal-care-41925',
    storageBucket: 'antenatal-care-41925.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDumKlQoQnGf6FdRqH8gJnG9jcNowLX8JA',
    appId: '1:64743673510:ios:74e500d46ef99fb07d2e67',
    messagingSenderId: '64743673510',
    projectId: 'antenatal-care-41925',
    storageBucket: 'antenatal-care-41925.appspot.com',
    iosBundleId: 'com.example.posSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDumKlQoQnGf6FdRqH8gJnG9jcNowLX8JA',
    appId: '1:64743673510:ios:d735c686d6c8aa057d2e67',
    messagingSenderId: '64743673510',
    projectId: 'antenatal-care-41925',
    storageBucket: 'antenatal-care-41925.appspot.com',
    iosBundleId: 'com.example.posSystem.RunnerTests',
  );
}
